[package]
name = "advent2025-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
cached = "^0.56"
log = "^0.4"
ndarray = "^0.17"
pathfinding = "4"
regex = "1"
serde = "1"
serde_with = "3"
strum = "^0.27"
strum_macros = "^0.27"

[dev-dependencies]
env_logger = "0.11.8"
test-log = "0.2.19"
