[package]
name = "advent2025-bin"
version = "0.1.0"
edition = "2024"

[dependencies]
advent2025-lib = { path = "../advent2025-lib" }
clap = "4.5.53"
color-eyre = "0.6.5"
colored = "3.0.0"
env_logger = "0.11.8"
indicatif = "0.18.3"
log = "0.4.28"
